workflows:
  main:
    name: Build and Test
    environment:
      vars:
        GRADLE_OPTS: -Dorg.gradle.java.home=/usr/lib/jvm/java-8-openjdk-amd64
    scripts:
      - name: Set up Java
        script: |
          echo "Installing JDK 8..."
          apt-get update
          apt-get install -y openjdk-8-jdk
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

      - name: Update Gradle Wrapper
        script: |
          echo "Updating Gradle Wrapper..."
          cd $FCI_BUILD_DIR
          chmod +x gradlew
          ./gradlew wrapper --gradle-version 7.2

      - name: Build
        script: |
          echo "Building the Java app..."
          cd $FCI_BUILD_DIR
          chmod +x gradlew
          ./gradlew build

      - name: Run Tests
        script: |
          echo "Running tests..."
          cd $FCI_BUILD_DIR
          chmod +x gradlew
          ./gradlew test
