workflows:
  version: 2
  build:
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
    scripts:
      - name: Build
        script: |
          ./gradlew assembleDebug
    artifacts:
      - build/app/outputs/apk/debug/app-debug.apk
