workflows:
  main:
    name: Build and Test
    environment:
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home

    scripts:
      - name: Set up Java
        script: |
          echo "Setting up Java..."
          export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home
          export PATH=$JAVA_HOME/bin:$PATH
          echo "Java setup completed."

      - name: Verify Java version
        script: |
          echo "Java version:"
          java -version
          javac -version

      - name: Build
        script: |
          echo "Building the Java app..."
          cd $FCI_BUILD_DIR
          chmod +x gradlew
          ./gradlew build --stacktrace
          echo "Build completed."

      - name: Run Tests
        script: |
          echo "Running tests..."
          cd $FCI_BUILD_DIR
          chmod +x gradlew
          ./gradlew test
          echo "Tests completed."

      - name: Archive APK
        script: |
          echo "Archiving APK..."
          cd $FCI_BUILD_DIR
          cp app/build/outputs/apk/debug/app-debug.apk $FCI_ARTIFACTS_DIR
          echo "APK archived."

    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
