workflows:
  main:
    name: Build and Test
    environment:
      vars:
        JAVA_HOME: /usr/lib/jvm/java-1.8.0-openjdk-amd64
    scripts:
      - name: Set up Java
        script: |
          echo "Installing JDK 8..."
          apt-get update
          apt-get install -y openjdk-8-jdk
          echo "JDK 8 installation completed."

      - name: Verify Java version
        script: |
          echo "Java version:"
          $JAVA_HOME/bin/java -version

      - name: Build
        script: |
          echo "Building the Java app..."
          cd $FCI_BUILD_DIR
          chmod +x gradlew
          $JAVA_HOME/bin/java -version
          $JAVA_HOME/bin/javac -version
          ./gradlew build
          echo "Build completed."

      - name: Run Tests
        script: |
          echo "Running tests..."
          cd $FCI_BUILD_DIR
          chmod +x gradlew
          $JAVA_HOME/bin/java -version
          $JAVA_HOME/bin/javac -version
          ./gradlew test
          echo "Tests completed."
