workflows:
  main:
    name: Build and Test
    environment:
      variables:
        - JAVA_HOME: /usr/lib/jvm/java-8-openjdk-amd64
    scripts:
      - name: Set up Java
        script: |
          echo "Installing JDK 8..."
          apt-get update
          apt-get install -y openjdk-8-jdk

      - name: Build
        script: |
          echo "Building the Java app..."
          cd app
          ./gradlew build

      - name: Run Tests
        script: |
          echo "Running tests..."
          cd app
          ./gradlew test
